version: "3"
services:

  proxy:
    # Use the latest v2.3.x Traefik image available
    image: traefik:v2.3
    restart: always
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - 80:80
      # Listen on port 443, default for HTTPS
      - 443:443
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount the volume to store the certificates
      - traefik-public-certificates:/certificates
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable Docker Swarm mode
      - --providers.docker.swarmmode
      # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Create an entrypoint "https" listening on port 443
      - --entrypoints.https.address=:443
      # Create the certificate resolver "le" for Let's Encrypt, uses the environment variable EMAIL
      - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
      # Store the Let's Encrypt certificates in the mounted volume
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      # Use the TLS Challenge for Let's Encrypt
      - --certificatesresolvers.le.acme.tlschallenge=true
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api

    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 3G
        reservations:
          cpus: '2'
          memory: 3G
      restart_policy:
        condition: on-failure
      labels:
        # Expose the service to the traefik proxy
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        # Define the port inside of the Docker service to use
        - traefik.http.services.proxy.loadbalancer.server.port=8080
        # Make Traefik use this domain in HTTP
        - traefik.http.routers.proxy-http.entrypoints=http
        - traefik.http.routers.proxy-http.rule=Host(`admin.pytemplates.gallery`)
        # Make Traefik use this domain in HTTPS
        - traefik.http.routers.proxy-https.entrypoints=https
        - traefik.http.routers.proxy-https.rule=Host(`admin.pytemplates.gallery`)
        - traefik.http.routers.proxy-https.tls=true
        # Use the "le" (Let's Encrypt) resolver created above
        - traefik.http.routers.proxy-https.tls.certresolver=le
        # https-redirect middleware to redirect HTTP to HTTPS
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.proxy-http.middlewares=https-redirect
        # admin-auth middleware with HTTP Basic auth
        # Using the environment variables USERNAME and HASHED_PASSWORD
        - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
        - traefik.http.routers.proxy-https.middlewares=admin-auth
        # Use the special Traefik service api@internal with the web UI/Dashboard
        - traefik.http.routers.proxy-https.service=api@internal

volumes:
  # Create a volume to store the certificates, there is a constraint to make sure
  # Traefik is always deployed to the same Docker node with the same volume containing
  # the HTTPS certificates
  traefik-public-certificates:

networks:
  traefik-public:
    external: true
